# Generated by Django 4.2.16 on 2026-03-20 17:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chronic_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpressurereading',
            name='diastolic',
            field=models.PositiveSmallIntegerField(help_text='Diastolic pressure in mmHg', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='bloodpressurereading',
            name='pulse',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Heart rate in bpm', null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AlterField(
            model_name='bloodpressurereading',
            name='systolic',
            field=models.PositiveSmallIntegerField(help_text='Systolic pressure in mmHg', validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='glucosereading',
            name='hba1c',
            field=models.FloatField(blank=True, help_text='HbA1c % if available from lab', null=True, validators=[django.core.validators.MinValueValidator(3.0), django.core.validators.MaxValueValidator(20.0)]),
        ),
        migrations.AlterField(
            model_name='glucosereading',
            name='value_mg_dl',
            field=models.FloatField(help_text='Blood glucose in mg/dL', validators=[django.core.validators.MinValueValidator(20.0), django.core.validators.MaxValueValidator(800.0)]),
        ),
        migrations.CreateModel(
            name='HealthGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_fasting_glucose_min', models.FloatField(blank=True, help_text='Target min fasting glucose mg/dL', null=True)),
                ('target_fasting_glucose_max', models.FloatField(blank=True, help_text='Target max fasting glucose mg/dL', null=True)),
                ('target_systolic_max', models.PositiveSmallIntegerField(blank=True, help_text='Target max systolic mmHg', null=True)),
                ('target_diastolic_max', models.PositiveSmallIntegerField(blank=True, help_text='Target max diastolic mmHg', null=True)),
                ('target_mood_score_min', models.PositiveSmallIntegerField(blank=True, help_text='Target minimum daily mood score', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_goal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
