# Generated by Django 4.2.16 on 2026-04-21 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WearableConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google_fit', 'Google Fit'), ('fitbit', 'Fitbit'), ('apple_health', 'Apple Health'), ('manual', 'Manual Entry')], max_length=20)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wearable_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='WearableReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('steps', 'Daily Steps'), ('heart_rate', 'Heart Rate (bpm)'), ('sleep_hours', 'Sleep Duration (hrs)'), ('calories', 'Calories Burned'), ('distance', 'Distance (km)'), ('glucose', 'Blood Glucose (mg/dL)'), ('oxygen_sat', 'Blood Oxygen (%)'), ('temperature', 'Body Temperature (°C)'), ('weight', 'Weight (kg)')], max_length=20)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('source', models.CharField(default='manual', help_text='google_fit | fitbit | apple_health | manual', max_length=20)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wearables.wearableconnection')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wearable_readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['patient', 'metric', '-recorded_at'], name='wearables_w_patient_52d363_idx')],
            },
        ),
    ]
