# Generated by Django 4.2.16 on 2026-04-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearables', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wearableconnection',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='wearablereading',
            name='wearables_w_patient_52d363_idx',
        ),
        migrations.AlterUniqueTogether(
            name='wearableconnection',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='wearableconnection',
            name='provider',
            field=models.CharField(choices=[('google_fit', 'Google Fit'), ('health_connect', 'Android Health Connect'), ('fitbit', 'Fitbit'), ('garmin', 'Garmin Connect'), ('apple_health', 'Apple Health (CSV)'), ('manual', 'Manual Entry')], max_length=20),
        ),
    ]
