# Generated by Django 4.2.16 on 2026-03-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='druginteraction',
            name='clinical_action',
            field=models.TextField(blank=True, help_text='Recommended clinical action'),
        ),
        migrations.AlterField(
            model_name='druginteraction',
            name='description',
            field=models.TextField(help_text='Plain-language description of the interaction risk'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='is_keml_listed',
            field=models.BooleanField(default=True, help_text='On Kenya Essential Medicines List'),
        ),
        migrations.AlterField(
            model_name='patientmedication',
            name='dosage',
            field=models.CharField(help_text='e.g. 500mg, 2 tablets', max_length=100),
        ),
        migrations.AlterField(
            model_name='patientmedication',
            name='end_date',
            field=models.DateField(blank=True, help_text='Leave blank for indefinite / chronic use', null=True),
        ),
    ]
