# Generated by Django 4.2.16 on 2026-03-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='duration_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How many days the symptom has been present', null=True),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='severity',
            field=models.PositiveSmallIntegerField(default=5, help_text='Patient-reported severity 1 (mild) to 10 (severe)'),
        ),
        migrations.AlterField(
            model_name='triagesession',
            name='layman_explanation',
            field=models.TextField(blank=True, help_text='Simplified explanation of possible causes'),
        ),
        migrations.AlterField(
            model_name='triagesession',
            name='matched_conditions',
            field=models.JSONField(default=list, help_text='Possible conditions identified by inference engine'),
        ),
        migrations.AlterField(
            model_name='triagesession',
            name='recommendation',
            field=models.TextField(blank=True, help_text='Plain-language advice for the patient'),
        ),
        migrations.AlterField(
            model_name='triagesession',
            name='red_flags_detected',
            field=models.JSONField(default=list, help_text='List of detected red-flag symptoms'),
        ),
    ]
