# Generated by Django 4.2.16 on 2026-03-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0002_alter_symptom_duration_days_alter_symptom_severity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagesession',
            name='explanation',
            field=models.JSONField(blank=True, default=dict, help_text='Structured explanation of why this triage decision was made.'),
        ),
    ]
