# Generated by Django 4.2.16 on 2026-03-20 17:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mental_health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copingstrategy',
            name='applicable_moods',
            field=models.JSONField(default=list, help_text='Mood categories this strategy is appropriate for'),
        ),
        migrations.AlterField(
            model_name='copingstrategy',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Suggested time to spend on this strategy', null=True),
        ),
        migrations.AlterField(
            model_name='copingstrategy',
            name='instructions',
            field=models.TextField(help_text='Step-by-step instructions in plain language'),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='emotions',
            field=models.JSONField(default=list, help_text="List of emotion tags e.g. ['anxious', 'tired', 'hopeful']"),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='journal_note',
            field=models.TextField(blank=True, help_text='Optional private journal entry (encrypted at rest in production)'),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='mood_score',
            field=models.PositiveSmallIntegerField(help_text='1 (very distressed) to 10 (excellent)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='triggers',
            field=models.TextField(blank=True, help_text='What may have caused this mood'),
        ),
        migrations.CreateModel(
            name='StrategyEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Effectiveness 1–5', null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_engagements', to=settings.AUTH_USER_MODEL)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='mental_health.copingstrategy')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
