# Generated by Django 4.2.16 on 2026-03-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_notification_doctorpatientrelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Profile photo for the user.', null=True, upload_to='profile_photos/'),
        ),
        migrations.DeleteModel(
            name='DoctorPatientRelationship',
        ),
    ]
