# Generated by Django 4.2.16 on 2026-03-23 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_profile_photo_delete_doctorpatientrelationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('status', models.PositiveSmallIntegerField()),
                ('duration', models.FloatField(help_text='Response time in milliseconds')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='authenticat_user_id_c5f5bc_idx'), models.Index(fields=['path'], name='authenticat_path_a6821d_idx'), models.Index(fields=['status'], name='authenticat_status_ad61b4_idx'), models.Index(fields=['-timestamp'], name='authenticat_timesta_5e2d47_idx')],
            },
        ),
    ]
