# Generated by Django 4.2.16 on 2026-04-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='transaction_external',
            field=models.CharField(blank=True, help_text='SHES transaction ID for this audit entry.', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(default='email', help_text="Authentication provider: 'email' for standard sign-up, 'google' for Google OAuth.", max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, help_text='Google OAuth ID for users who sign up via Google.', max_length=255, null=True, unique=True),
        ),
    ]
