# Generated by Django 4.2.16 on 2026-04-21 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auditlog_transaction_external_user_auth_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('glucose', 'Glucose Management'), ('blood_pressure', 'Blood Pressure'), ('mood', 'Mental Health'), ('medication', 'Medication'), ('lifestyle', 'Lifestyle'), ('triage', 'Medical Review'), ('wearable', 'Activity & Fitness'), ('lab', 'Lab Results')], max_length=20)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('icon', models.CharField(default='💡', max_length=10)),
                ('completed', models.BooleanField(default=False)),
                ('dismissed', models.BooleanField(default=False)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': [models.Case(models.When(priority='urgent', then=0), models.When(priority='high', then=1), models.When(priority='medium', then=2), models.When(priority='low', then=3), default=4, output_field=models.IntegerField()), '-created_at'],
            },
        ),
    ]
