# Generated by Django 4.2.16 on 2026-03-25 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.BigIntegerField(db_index=True, unique=True)),
                ('external_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('record_type', models.CharField(choices=[('lab_result', 'Lab Result'), ('alert', 'Alert'), ('triage', 'Triage Session'), ('risk_report', 'Risk Report'), ('medication', 'Medication Record'), ('audit_log', 'Audit Log'), ('generic', 'Generic')], default='generic', max_length=20)),
                ('reference_id', models.CharField(blank=True, help_text='Optional: UUID of the related SHES record (lab result, triage session, etc.)', max_length=100)),
                ('machine_id', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction Record',
                'verbose_name_plural': 'Transaction Records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['record_type', '-created_at'], name='transaction_record__96fa54_idx'), models.Index(fields=['issued_to', '-created_at'], name='transaction_issued__4cab42_idx')],
            },
        ),
    ]
